Blog/Controllers/AdminThingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Blog.Models;
using Blog.Models.Service;

namespace Blog.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminThingsController : Controller
    {
        private Service service = new Service();

        public ActionResult PostCreator()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Posted(Post post)
        {
            post.Date = DateTime.Now;
            post.Likes = 0;

            if (!ModelState.IsValid)
                return View("PostCreator", post);

            service.AddPost(post);

            return RedirectToAction("Posts", "MainContent");
        }
    }
}

Blog/Controllers/AjaxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blog.Controllers
{
    public class AjaxController : Controller
    {
        // GET: Ajax
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Table()
        {        
            return View();
        }

        public ActionResult Test()
        {
            return View();
        }
    }
}

Blog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Randomowy blog - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Randomowy Blog", "Index", "MainContent", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Posty", "Posts", "MainContent")</li>
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("Napisz Post", "PostCreator", "AdminThings")</li>
                    }                    
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">AJAX<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Ostatni Post", "Index", "Ajax")</li>                           
                            <li class="divider"></li>
                            <li>@Html.ActionLink("Tabelka", "Table", "Ajax")</li>
                            <li class="divider"></li>
                            <li>@Html.ActionLink("Test", "Test", "Ajax")</li>
                        </ul>
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Randomowy Blog by Tomasz Łyszkiewicz</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>