Blog/Models/Post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blog.Models
{
    public class Post
    {
        public Post()
        {
            this.Comments = new HashSet<Comment>();
        }

        public int PostId { get; set; }

        [Required(ErrorMessage = "Musisz wpisać coś w Tytule"), Display(Name = "Tytuł Postu")]
        [StringLength(70, ErrorMessage = "Maksymalna liczba znaków: 70")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Musisz wpisać coś w poście"), Display(Name = "Post")]
        [StringLength(5000, ErrorMessage = "Maksymalna liczba znaków: 5000")]
        [AllowHtml]
        public string Text { get; set; }

        [Required, Display(Name = "Data")]
        public DateTime Date { get; set; }

        [Required(ErrorMessage = "Kim jesteś?"), Display(Name = "Autor")]
        public string Author { get; set; }
        public int Likes { get; set; }

        public virtual ICollection<Comment> Comments { get; set; }
    }
}

Blog/Controllers/Api/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading;
using System.Web.Http;
using Blog.Models;
using System.Data.Entity;

namespace Blog.Controllers.Api
{
    public class PostController : ApiController
    {

        private ApplicationDbContext _context;

        public PostController()
        {
            _context = new ApplicationDbContext();
        }

        [HttpGet]
        public IHttpActionResult Posts()
        {
            var post = _context.Posts.ToList().OrderByDescending(p => p.Date).FirstOrDefault();          
            if (post == null)
                NotFound();
            Thread.Sleep(2000);

            return Ok(post);
        }

        [HttpGet]
        public IHttpActionResult Posts(int id)
        {
            var post = _context.Posts.Include(p=> p.Comments).SingleOrDefault(p => p.PostId == id);
            if (post == null)
                return NotFound();

            return Ok(post);
        }
    }
}

Blog/Controllers/MainContentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Blog.Models;
using Blog.Models.Service;
using Blog.ViewModels;

namespace Blog.Controllers
{
    public class MainContentController : Controller
    {
        private Service service = new Service();

        public ActionResult Index()
        {
            var posts = service.GetPosts(5);

            return View(posts);
        }

        public ActionResult Posts()
        {
            var posts = service.GetPosts();
            return View(posts);
        }

        public ActionResult ShowPost(int id)
        {
            var post = service.GetPostById(id);
            if (post == null)
                return HttpNotFound();
                       
            var vm = new PostCommentViewModel
            {
                Post = post,
                Comment = new Comment(),
                Comments = service.GetCommentsByPostId(post.PostId),
            };

            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SaveComment(Comment comment, int id)
        {
            comment.Likes = 0;
            comment.Date = DateTime.Now;
            comment.PostId = id;
            comment.User = User.Identity.Name;

            //if (!ModelState.IsValid)
            //    return RedirectToAction("ShowPost", new { id = id });

            service.AddComment(comment);

            return RedirectToAction("ShowPost", new { id = id });
        }
    }
}

Blog/Views/MainContent/Index.cshtml
@model IEnumerable<Blog.Models.Post>

@{
    ViewBag.Title = "Start";
}

<div class="jumbotron">
    <h2>Witaj</h2>
    <p>na moim randomowym blogu, na którym to będę uczył się, testował a przedewszystkim bawił poznawanymi technologiami.</p>
</div>
<hr />
<div class="container">
    <div class="row">
        <div class="container">
            <h2>Ostatnie wpisy</h2>
            @foreach (var post in Model)
            {
                <div class="post col-md-8">
                    <h3>@post.Title</h3>
                    <p>
                        @post.Date <br />
                        autor: @post.Author
                    </p>
                    @if (post.Text.Count() <= 170)
                    {
                    <p class="post-text">@Html.Raw(System.Web.HttpUtility.HtmlDecode(post.Text))</p>
                    }
                    else
                    {
                    <p class="post-text">@Html.Raw(System.Web.HttpUtility.HtmlDecode(post.Text)).ToString().Remove(170)...</p>
                    }
                    <p>
                        Polubienia: @post.Likes
                        @Html.ActionLink("Zobacz posta", "ShowPost", "MainContent", new { id = post.PostId }, new { @class = "btn btn-link btn-xs" })
                    </p>
                </div>

            }
        </div>
        <div class="col-md-4">

        </div>
    </div>
</div>

Blog/Views/MainContent/Posts.cshtml
@model IEnumerable<Blog.Models.Post>
@{
    ViewBag.Title = "Posts";
}

<h2>Posty</h2>
<div class="container">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="post col-md-8" data-post-id=@item.PostId>
                @Html.Partial("_Post", item)
                <p>@Html.ActionLink("Komentarze (" + item.Comments.Count + ")", "ShowPost", new { id = item.PostId }, new { @class = "btn btn-success btn-xs" })</p>
            </div>
        }
    </div>
</div>

@section scripts
    {

    @if (User.Identity.IsAuthenticated)
    {
        <script>
            $(document).ready(function () {
                $.post("/api/like/showLike", { userLogin: $(".js-like").attr("data-user-name") }, function (data) {
                    $.each(data, function (n, v) {
                        $(".post").each(function (z, x) {
                            if (v.postId == x.getAttribute("data-post-id")) {
                                if (v.isLike) {
                                    $(".js-like[data-post-id=" + v.postId + "]").css("color", "blue");
                                }
                                else if (!v.isLike) {
                                    $(".js-dislike[data-post-id=" + v.postId + "]").css("color", "red");
                                }
                            }
                        });
                    })
                });

                $(".js-like").on("click", function () {
                    var postLike = {
                        postId: $(this).attr("data-post-id"),
                        userLogin: $(this).attr("data-user-name"),
                        isLike: true
                    };
                    $.post("/api/like/addlike/", postLike)
                        .done(function (data) {
                            $(".js-like[data-post-id=" + postLike.postId + "]").parent().siblings("#likes").text(data.likes);
                            $(".js-dislike[data-post-id=" + postLike.postId + "]").css("color", "grey");
                            $(".js-like[data-post-id=" + postLike.postId + "]").css("color", "blue");

                        });
                });

                $(".js-dislike").on("click", function () {
                    var postLike = {
                        postId: $(this).attr("data-post-id"),
                        userLogin: $(this).attr("data-user-name"),
                        isLike: false
                    };
                    $.post("/api/like/addlike/", postLike)
                        .done(function (data) {
                            $(".js-dislike[data-post-id=" + postLike.postId + "]").parent("span").siblings("#likes").text(data.likes);
                            $(".js-like[data-post-id=" + postLike.postId + "]").css("color", "grey");
                            $(".js-dislike[data-post-id=" + postLike.postId + "]").css("color", "red");
                        });
                });
            });
        </script>
    }
}

Blog/Views/MainContent/ShowPost.cshtml
@model Blog.ViewModels.PostCommentViewModel
@{
    ViewBag.Title = Model.Post.Title + " by " + Model.Post.Author;
}

<div class="container">


    <div class="container">
        <div class="row">
            <div class="container post col-md-8">
                @Html.Partial("_Post", Model.Post)
                @if (!User.Identity.IsAuthenticated)
                {
                    @Html.ActionLink("Zaloguj się", "Login", "Account", new { returnUrl = Request.Url.ToString() }, new { @class = "btn btn-success btn-sm" })
                    <span>aby skomentować post</span>
                }
                else
                {
                    <button id="js-comment" class="btn btn-success btn-sm">Skomentuj</button>
                }
            </div>
        </div>
        <div class="container">
            <div id="js-content" class="post col-md-5" style="display:none">
                @using (Html.BeginForm("SaveComment", "MainContent", new { id = Model.Post.PostId }))
                {
                    @Html.AntiForgeryToken()
                    <div class="row">
                        <div class="form-group col-md-10">
                            @Html.LabelFor(m => m.Comment.Text)
                            @Html.TextAreaFor(m => m.Comment.Text, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Comment.Text)
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-4">
                            <label class="control-label">@User.Identity.Name</label>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-2">
                            <button type="submit" class="btn btn-primary btn-sm">Wyślij</button>
                        </div>
                    </div>

                }
            </div>
        </div>
        <div class="container">
            <h4>Komentarze (@Model.Comments.Count)</h4>
            <div class="comment col-md-6">
                @foreach (var comment in Model.Comments)
                {
                    <div class="row">
                        <div class="comment-row">
                            <p>@comment.Date</p>
                            <p>@comment.User napisał(a):</p>
                            <p class="comment-text">@comment.Text</p>
                            @*<p>Lubiki: @comment.Likes</p>*@
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>


@section scripts{

    @if (User.Identity.IsAuthenticated)
    {
        <script>
            $(document).ready(function () {

                $.post("/api/like/showLike", {
                    postId: $(".js-like").attr("data-post-id"),
                    userLogin: $(".js-like").attr("data-user-name")
                }, function (data) {
                    if (data.isLike) {
                        $(".js-like").css("color", "blue");
                    }
                    else if (!data.isLike) {
                        $(".js-dislike").css("color", "red");
                    }
                });

                $(".js-like").on("click", function () {
                    var postLike = {
                        postId: $(this).attr("data-post-id"),
                        userLogin: $(this).attr("data-user-name"),
                        isLike: true
                    };
                    $.post("/api/like/addlike/", postLike)
                        .done(function (data) {
                            $("#likes").text(data.likes);
                            $(".js-dislike").css("color", "grey");
                            $(".js-like").css("color", "blue");

                        });
                });

                $(".js-dislike").on("click", function () {
                    var postLike = {
                        postId: $(this).attr("data-post-id"),
                        userLogin: $(this).attr("data-user-name"),
                        isLike: false
                    };
                    $.post("/api/like/addlike/", postLike)
                        .done(function (data) {
                            $("#likes").text(data.likes);
                            $(".js-like").css("color", "grey")
                            $(".js-dislike").css("color", "red");
                        });
                });
            });
        </script>
    }

    <script>
        $(document).ready(function () {
            $("#js-comment").on("click", function () {
                $("#js-content").slideToggle(1500);
            });
        });
    </script>

    @Scripts.Render("~/bundles/jqueryval")
}

Blog/Views/MainContent/_Post.cshtml
@model Blog.Models.Post

<h3>@Model.Title</h3>
<p>@Model.Date <br /> autor: @Model.Author</p>
<p class="post-text">@Html.Raw(System.Web.HttpUtility.HtmlDecode(Model.Text))</p>
<p>
    Polubienia: <span id="likes">@Model.Likes</span>
    @if (User.Identity.IsAuthenticated)
    {
        <span>&nbsp;&nbsp;<i class="glyphicon glyphicon-thumbs-up js-like" data-post-id=@Model.PostId data-user-name=@User.Identity.Name></i></span>
        <span>&nbsp;&nbsp;<i class="glyphicon glyphicon-thumbs-down js-dislike" data-post-id=@Model.PostId data-user-name=@User.Identity.Name></i></span>
    }
</p>